name: dev-build

#this drops to github with beta tag?

on:
  push:
    branches: [ dev]
  pull_request:
    branches: [ dev, main ]

  workflow_dispatch:

jobs:
  build:
    name: Build Comet-Nuget
    env:
        NUPKG_MAJOR: 0.2
        BASE: 334
    runs-on: windows-latest

    steps: 
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Install Visual Studio Preview
        shell: pwsh
        run: powershell .\build\install-vs.ps1
      
      # - name: Add msbuild to PATH
      #   uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Add MSBuild to Path
        shell: pwsh
        run: |
          dotnet tool update -g dotnet-vs
          & echo "$(vs where preview --prop=InstallationPath)\MSBuild\Current\Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
      - name: Install and Run maui-check Tool
        shell: pwsh
        run: |
          & dotnet tool update --global redth.net.maui.check
          & maui-check --preview --verbose --non-interactive --fix --skip androidsdk --skip xcode --skip vswin --skip vsmac --skip edgewebview2
     
      - name: Restore Comet-Nuget.sln
        run: nuget restore build/Comet-Nuget.sln

      - name: Build Comet-Nuget.sln
        run: msbuild build/Comet-Nuget.sln

      - name: Restore Comet-net6-Nuget.sln
        run: dotnet restore build/Comet-net6-Nuget.sln
 
      - name: Build Comet-net6-Nuget.sln
        run: MSBuild build/Comet-net6-Nuget.sln
        
      - name: Nuget Pack step
        shell: bash
        run: |
          MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
          VERSION=0.3.$MINOR_VERSION-alpha
          echo "PACKAGE VERSION: $VERSION"
          nuget pack Comet.nuspec -version $VERSION -Symbols -SymbolPackageFormat snupkg

      - name: Nuget Pack Template step
        shell: bash
        run: |
          MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
          VERSION=0.3.$MINOR_VERSION-alpha
          echo "PACKAGE VERSION: $VERSION"
          nuget pack "templates\comet-templates.nuspec" -version $VERSION
                    
      - uses: actions/upload-artifact@v2
        name: Upload Nuget Artifact
        with:
          name: nuget-artifact
          path: |
            **\*.nupkg
            **\*.snupkg
            **\*.symbols.nupkg

      - name: Restore Comet-Tests.sln
        run: nuget restore build/Comet-Tests.sln

      - name: Build Tests Project
        run: msbuild tests/Comet.Tests/Comet.Tests.csproj /p:Configuration=Release
        
      - name: Run Tests Project
        run: dotnet test tests/Comet.Tests/Comet.Tests.csproj
      
